name: CI for ARM64 on main

on:
  push:
    branches: 
      - 'main'
  
jobs:
  build_on_arm64:
    name: Build on ARM64
    uses: './.github/workflows/ci.yml'
    with:
      runner: self-hosted
    # runs-on: self-hosted
    