name: Regression and Unit Testing

on:
  pull_request:
    branches: 
      - 'main'
  workflow_call:
    workflows: ["CI for ARM64 on main"]
    types: [requested]
    branches:
      - 'main'


jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "Step 1 is ran"
        