name: Regression and Unit Testing

on:
  pull_request:
    branches: 
      - 'main'
  workflow_call:
    # workflows: ["CI for ARM64 on main"]
    # types: [requested]
    inputs:
      runner:
        description: 'The github runner to use'
        default: 'ubuntu-latest'
        required: false
        type: string
    # branches:
      # - 'main'


jobs:
  build1:
    name: Build 1
    runs-on: ${{ inputs.runner || 'self-hosted' }}
    steps:
      - name: Step 1
        run: echo "Step 1 is ran"
  build2:
    name: Build 2
    runs-on: ${{ inputs.runner || 'self-hosted' }}
    steps:
      - name: Step 2
        run: lscpu
        